name: Test
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: [lint]
    strategy:
      matrix:
        version: [14, 16, 18]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: Install deps
        run: npm ci
      - name: Test
        run: npm run test
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: echo ${{ secrets.TEST_SECRET_WORD }}
  